# Generated by Django 3.0.5 on 2020-06-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200614_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(default='', max_length=300)),
                ('address2', models.CharField(default='', max_length=300)),
                ('zip_code', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
